language: bash
dist: xenial
services:
  - docker

env:
  global:
    - secure: Wq6N6j7DDXJgNB1fD4mm7kLn2y7zSko/Ym5Nl7A3nAodYD4s8rSzak0ywm11+M8M2li9AneICskF8/KO/Ol3B93a+/DtIXaF8Nsx4NPLN+bEdS96M8hz5puTRUyzMLYWGK9sKfQJogsa4HvmVc2HysoSHVpFaEPTrQPeb+c26thmIsOBcsRqA9OV8/uMdT41ICf1L89ZGjzIhhSmNKycRBR4FwQdzJ8a9NGBEyNmDFS7hvlqR86MQB6s3Y92wycOVzonYq4JAugwophmdM1Siy/iORshfBIQ0rPCl2+WavjudRwgkQ8GOSsqX2BkimOk3tManNbSOfDkKOTiUxJZcojfkLaUuUKQOZ6KT4bxePrqS+Bbfm5p9hKZ0kJQH3pR8W0cjgAP4Ac+ygyGBCcQmaBQC5SL/D3pBMhl1uFijk0+aNBB+xbmBAdgjsaDqfUdc61QWFmNBq+tCJHOZ7RMK0PPRveQHUOSnr7oaDeoxDAtCXIQTFS30bNJ2gc85GZ5uEgXhBP72IgLtgVLnvVaJrBBIV77Fjp1CfnLIFj4PxfIGvlbBQ6OkonNtWsggUOPFUELD8VJW67u0fKY4eihf2yZlJJJwi9AXkLl2MjzVOEobQkXq4q3wjKhKfOW3KLGlcS/QgKG97SCAM5Wy1pfXF5Kb7b2FxdRXVmmtOlHhac=

before_install:
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" >> env.list
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH" >> env.list
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" >> env.list
  - echo "ENCRYPTED_PRIVKEY_SECRET=$ENCRYPTED_PRIVKEY_SECRET" >> env.list
  - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> env.list
  - echo "DISABLE_ID_CHECK=1" >> env.list
  - wget https://raw.githubusercontent.com/openSUSE/doc-ci/master/travis/travis.sh

script:
  - docker run --rm -it --volume ${PWD}:/usr/src/app --workdir /usr/src/app susedoc/ci:latest /bin/bash -c '/bin/bash travis.sh'

notifications:
  email:
    on_success: change
    on_failure: always
