== Notes for installing SUSE Cloud Application Platform on Microsoft Azure

=== Requirements

To setup the Microsoft Azure environment the command line client *az* is required.

* On SUSE systems it can be installed by executing the following commands:
+
[source,bash]
----
$ sudo zypper install -y curl
$ sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
$ sudo sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/zypp/repos.d/azure-cli.repo'
$ sudo zypper refresh
$ sudo zypper install -y azure-cli
----

* Login to Azure
+
[source,bash]
----
$ az login
----

=== Setup of Kubernetes

* The subscriptions ID needs to be exctracted and written down:
+
[source,bash]
----
$ az account show --query "{ subscription_id: id }"
----


* Create a service principal and write down the _password_ and _appId_.
The term _<subscription-id>_ needs to be replaced by the _subscription_id_ noted in the in the previous step. If the Microsoft Azure service is supposed to be located in another data center then in the Western USA _westus_ needs to be replaced. 
+
[source,bash]
----
$ export SUBSCRIPTION_ID=<subscription-id>
$ az account set --subscription $SUBSCRIPTION_ID
$ az group create --name scf-resource-group --location westus
$ az ad sp create-for-rbac --role Contributor --scopes "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/scf-resource-group"
----

* Create a container service in Azure and replace the terms _<password>_ and _<application-id>_ by the one noted from the previous step. Additionally the phrase _<your-publi- ssh-key>_ should be replaced by the public ssh key to be used:
+
[source,bash]
----
$ az acs create \
       --name scf-container-service \
       --resource-group scf-resource-group \
       --orchestrator-type Kubernetes \
       --dns-prefix "myscf" \
       --master-count 1 \
       --admin-username scf-admin \
       --agent-count 3 \
       --client-secret <password> \
       --ssh-key-value "<your-publi- ssh-key>" \
       --service-principal <application-id> \
       --master-vm-size Standard_D2_v2
----

* Prepare kubernetes environment. If there is already another running Kubernetes it is advised to backup the old configuration located in '~/.kube/'.
+
[source,bash]
----
$ az acs kubernetes get-credentials --resource-group="scf-resource-group" --name="scf-container-service"
----

* The Kubernetes config can be verified by listing all the current pods.
+
[source,bash]
----
$ kubectl get pods --all-namespaces
----

* Enable cgroup swap accounting by running the following commands. This will reboot some of the machines which takes some time.
+
[source,bash]
----
$ az vm list --g "scf-resource-group" | jq '.[] | select (.tags.poolName | contains("agent")) | .name' | \
  xargs -i{} az vm run-command invoke \
    --resource-group "scf-resource-group" \
    --command-id RunShellScript \
    --scripts "sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"console=tty1 console=ttyS0 earlyprintk=ttyS0 rootdelay=300\"/GRUB_CMDLINE_LINUX_DEFAULT=\"console=tty1 console=ttyS0 earlyprintk=ttyS0 rootdelay=300 swapaccount=1\"/g' /etc/default/grub.d/50-cloudimg-settings.cfg" --name {}

$ az vm list -g "scf-resource-group" | jq '.[] | select (.tags.poolName | contains("agent")) | .name' | \
  xargs -i{} az vm run-command invoke \
    --resource-group "scf-resource-group" \
    --command-id RunShellScript \
    --scripts "sudo update-grub" --name {}

$ az vm list -g "scf-resource-group" | jq '.[] | select (.tags.poolName | contains("agent")) | .name' | \
  xargs -i{} az vm restart --no-wait \
    --resource-group "scf-resource-group" \
    --name {}
----

* Create a new public ip address and write it down.
+
[source,bash]
----
$ az network public-ip create --resource-group scf-resource-group --name scf-public-ip --allocation-method Static
----


* Extract the name of one of the kubes agent nic and write it down
+
[source,bash]
----
$ az network nic list --resource-group scf-resource-group | grep name | grep agent | grep 0
----

* Attach the public ip to the master kubes node by replacing the term _<nic-name>_ by the one noted down before and write down the value of _privateIpAddress_.
+
[source,bash]
----
$ az network nic ip-config update --resource-group scf-resource-group --nic-name <nic-name> --name ipconfig1 --public-ip-address scf-public-ip
----


* Extract the security group name of the master network security group and write it down
+
[source,bash]
----
$ az network nsg list --resource-group=scf-resource-group | jq -r '.[] | .name' | grep master
----


* Create required security groups and replace _<security-group>_ by the name wrote down in the step before.
+
[source,bash]
----
$ export NSG_NAME=<security-group>
$ az network nsg rule create --resource-group scf-resource-group --priority 200 --nsg-name $NSG_NAME --name scf-80 --direction Inbound --destination-port-ranges 80 --access Allow
$ az network nsg rule create --resource-group scf-resource-group --priority 201 --nsg-name $NSG_NAME --name scf-443 --direction Inbound --destination-port-ranges 443 --access Allow
$ az network nsg rule create --resource-group scf-resource-group --priority 202 --nsg-name $NSG_NAME --name scf-4443 --direction Inbound --destination-port-ranges 4443 --access Allow
$ az network nsg rule create --resource-group scf-resource-group --priority 203 --nsg-name $NSG_NAME --name scf-2222 --direction Inbound --destination-port-ranges 2222 --access Allow
$ az network nsg rule create --resource-group scf-resource-group --priority 204 --nsg-name $NSG_NAME --name scf-2793 --direction Inbound --destination-port-ranges 2793 --access Allow
----
