== SUSE Cloud Application Platform Release Notes

This repository contains the release notes for SUSE Cloud Application Platform.

=== Published Version of the Release Notes

These release notes are published at
https://www.suse.com/releasenotes/x86_64/SUSE-CAP/2.0/.
This published version is automatically updated from the `master` branch every
24 hours.


=== Preview Versions of the Release Notes

You can preview these release notes in the following two ways:

* Documents built by Travis CI: https://susedoc.github.io/#cap-rn
** These previews are indicative of how the final document will look like.
** The builds from Travis are updated automatically after every commit (with
   a delay of ten minutes or less).
* Make sure to pick the right branch to preview. Branches need to be
  specifically configured for publishing on this page -- for more
  information, see <<sec.branch-builds>>).

* Use the GitHub preview: link:adoc/MAIN.release-notes.adoc[]
** This preview mode is not 100% indicative of the final output.
** Not everything will look perfect: you may happen upon bare attribute entries
   (`{}`) and embedded sections will appear as a link only.
** This preview mode is updated immediately and available for all branches.

For technical details on the differences between the preview builds, see
<<sec.preview-difference>>.


=== Additional Documentation Resources on SUSE CAP

* For full documentation of SUSE Cloud Application platform, please refer to the link:https://documentation.suse.com/suse-cap/2.0/[official documentation].
* More details about special use cases can currently be found in the instructions for the following SUSE-driven open-source projects:
** link:https://github.com/cloudfoundry/stratos/tree/master/deploy/kubernetes[Stratos UI]
* Generic Cloud Foundry documentation is in the link:https://docs.cloudfoundry.org[upstream docs].


==== Documentation for Special Environments

* link:https://documentation.suse.com/suse-caasp/4.2/html/caasp-deployment/[SUSE CaaS (Container as a Service) Platform & Bare Metal or Non-OpenStack Virtualization Platforms]
* link:https://documentation.suse.com/soc/8/html/suse-openstack-cloud-clm-all/install-heat-templates.html#sec-heat-templates-install[SUSE CaaS (Container as a Service) Platform & SUSE OpenStack Cloud]
* link:https://documentation.suse.com/suse-cap/2.0/html/cap-guides/cha-cap-depl-aks.html[Microsoft Azure Platform]


=== Contributing

Want to help? We love to hear that!


==== Document Format

These release notes are written in the AsciiDoc (`*.adoc`) format. For some
great AsciiDoc documentation, see https://asciidoctor.org/docs/asciidoc-writers-guide


==== Submitting Changes

To submit new changes for review, use GitHub pull requests. Travis CI will
automatically check whether your pull request's content is compatible AsciiDoc.
However, as AsciiDoc is a plain-text based format, it is important to visually
verify that everything is correct using one of the previews.


==== Previewing Locally

On a computer with openSUSE or SLES/SLED, you can use DAPS (or `daps2docker`) to
generate preview documents as HTML, PDF, or plain-text.

* Using `daps2docker` -- Building this way is a bit heavy-handed but it
  generally sidesteps issues with the DAPS version on your platform or issues
  with PDF generation and should work on any Linux distribution that Docker
  is available on:
+
. Install the package `daps2docker` from `https://build.opensuse.org/project/show/Documentation:Tools`.
. From the main directory of this repository, run `daps2docker DC-release-notes`
  (generates PDF and HTML)

* Using DAPS -- This is the way that the internal OBS instance builds the
  published release notes:
+
. Install the package `daps` from the openSUSE or SLE repositories. Make
   sure your DAPS version is 3.0 or higher and the package
   `ruby__x.x__-rubygem-asciidoctor` is installed (replace `x.x` with an
   appropriate version of Ruby).
. Run `make all` (generates PDF, HTML, text file, and HTML for YaST)


[id='sec.branch-builds']
==== Enabling susedoc.github.io Preview Builds for Specific Branches

On link:https://susedoc.github.io/#cap-rn[], previews are built only for
specific branches that are configured at link:https://github.com/SUSEdoc/susedoc.github.io[].
To enable your feature branch for builds, the XML configuration file in that
repository needs to be changed. You may not have write access to this
repository but you can create a Pull Request for that repository or ask any
of @sknorr, @fsundermeyer, @btat, or @gaktive to change the configuration for
you.


[id='sec.preview-difference']
==== Technical Differences Between GitHub Preview and Final Version

* GitHub will simply render a preview of a single `*.adoc` file using
AsciiDoctor's built-in HTML conversion. This README links to individual content
files.
* The SUSE Web site build combines multiple `*.adoc` files into a single HTML
output file. It is based on AsciiDoctor's AsciiDoc-to-DocBook-XML conversion,
the result of which is then further converted into HTML/PDF using DAPS and the
DocBook XSL stylesheets. The central file for this build is
`adoc/MAIN.release-notes.adoc` which includes individual content files.

* To change any of the "attribute entries" (the text macros containing product
names at the top of files):
  . Edit `adoc/entities.adoc` to your heart's content (these are used for the
  SUSE Web site build)
  . Run `make update-entries` to update the dependent attribute entries in each
  of the `*.adoc` files (these are used for GitHub previews).
