== Release Notes SUSE Cloud Application Platform 1.1

These are the release notes for SUSE Cloud Application Platform 1.1. It contains additional information specific to the current release. See the link:https://www.suse.com/documentation/cloud-application-platform-1/[Deployment Guide] for details information how to deploy the product.

=== Known issues

IMPORTANT: You will need Stratos UI 1.1 when running SUSE Cloud Application Platform 1.1 and you share the `scf-values.yaml` configuration file between them. Prior versions of the Stratos UI will not work.

IMPORTANT: When you have used a configuration file from a version prior to 1.1 you will need to make some adations. See details below. 

* Changes to working with upgrades: 
** The variable `kube.external_ip` has now been changed to `kube.external_ips`, meaning upgrades from older versions will fail unless the latter variable exists in the `scf-values.yaml` file used to deploy Cloud Application Platform. Both variables can exist at the same time and be set to the same value for those in mixed version environments: 
+
> kube.external_ip=1.1.1.1 
+
> kube.external_ips=[1.1.1.1] 

** Going forward, `kube.external_ips` is an array, so usage would be like so: 
+
> kube.external_ips=[“1.1.1.1”, “2.2.2.2”] 

** Also as a result of this change, the `helm` command line client must be version 2.6.0 or higher. 
** All the secrets have been renamed from `env.FOO` to `secrets.FOO`, so all the appropriate entries in `scf-values.yaml` need to be modified to align with that change. 
** You need to keep specifying *all* your secrets on each upgrade (e.g. the `CLUSTER_ADMIN_PASSWORD`) as it won't be carried forward automatically. 
** To rotate secrets, increment the `kube.secret_generation_counter` (Please note: immutable generated secrets will not be reset.)
* For upgrading SUSE Cloud Application Platform 1.0.1 to 1.1 run the following commands, e.g.:
[source,bash]
$ helm repo update
$ helm upgrade --recreate-pods <uaa-helm-release-name> suse/uaa --values scf-config-values.yaml
$ SECRET=$(kubectl get pods --namespace uaa -o jsonpath='{.items[*].spec.containers[?(.name=="uaa")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretKeyRef.name}')
$ CA_CERT="$(kubectl get secret $SECRET --namespace uaa -o jsonpath="{.data['internal-ca-cert']}" | base64 --decode -)"
$ helm upgrade --recreate-pods <scf-helm-release-name> suse/cf --values scf-config-values.yaml --set "secrets.UAA_CA_CERT=${CA_CERT}"
$ helm upgrade --recreate-pods <console-helm-release-name> suse/console --values scf-config-values.yaml
* Upgrades on HA environment have run into an issue whereby the api pods don’t all come up post-migration. The workaround is prior to running the upgrade, scale down the api role to 1. Then upon completing the upgrade, scale api up again to 2 or more. 
** Some roles (like diego-api, diego-brain and routing-api) are configured as active/passive, so passive pods can appear as `Not Ready`.
** Other roles (tcp-router and blobstore) cannot be scaled. 
* Cloud Application Platform v1.1 requires that Stratos UI use version 1.1; older versions of the UI will not work due to the change in variable names. 
* Azure operators may not be able to connect to SQL databases with the sidecar. 
* Restores performed by the Backup CLI may leave docker apps in a stopped state. The workaround is to restart the affected applications. 
* A proper JSON file generated by the Backup CLI needs to be provided in order to do a restore, otherwise an ugly error appears. 
* Do not set the `mysql` or `diego_access` roles to more than one instance each in HA configurations. Doing so can cause problems with subsequent upgrades which could lead to loss of data. Scalability of these roles will be enabled in an upcoming maintenance release. 
* A `helm upgrade` command from 1.0 to 1.0.1 (scf 2.6.11 to 2.7.0) requires the use of `--force` to drop an unnecessary persistent volume. Note that `helm upgrade` only works for multi-node clusters when running with a proper HA storage class (e.g. `hostpath` will not work as required stateful data can be lost). 

== 1.1 Release April, 2018

* Support for Azure AKS 
* Backup/restore cf CLI plugin 
* Helm charts for PostgreSQL and MySQL service broker sidecars 
* Ability to specify multiple external IP addresses (please see Known Issues below on impact to upgrades)  
* MySQL now a clustered role 
* Mysql-proxy enabled for UAA 
* UAA has more logging enabled, so `SCF_LOG_HOST`, `SCF_LOG_PORT` and `SCF_LOG_PROTOCOL` have been exposed 
* TCP routing ports are configurable and can be templatized 
* CPU limits can be set 
* Kubernetes annotations enabled so operators can specify what nodes particular roles can be run on 
* Fixed cloud controller clock so that it will wait until API is ready 
* Overhauled how secret rotation works regarding to upgrades 
* Pods no longer random fail to start occasionally 
* Includes these CF component versions 
** diego-release: 1.35 
** cf-mysql-release: 36.10.0 
** cflinuxfs2-release: 1.187.0 
** routing-release: 0.172.0 
** garden-runc-release: 1.11.1 
** nats-release: 22 
** capi-release: 1.49.0 
* Includes these CF buildpack versions 
** go-buildpack-release: 1.7.19-16-g37cc6b4 
** binary-buildpack-release: 1.0.17 
** nodejs-buildpack-release: 1.5.30-13-g584d686 
** ruby-buildpack-release: 9adff61 
** php-buildpack-release: ea8acd0 
** python-buildpack-release: 1.5.16-14-ga2bbb4c 
** staticfile-buildpack-release: 1.4.0-12-gdfc6c09 
** dotnet-core-buildpack-release: 1.0.26-14-gf951834 
** java-buildpack-release: 3.16-18-gfeab2b6 

== 1.0.1 Release February, 2018

* Bump to CF Deployment (1.9.0), using CF Deployment not CF Release from now on
* Bump UAA to v53.3
* Add ability to rename immutable secrets
* Update CATS to be closer to what upstream is using
* Make RBAC the default in the values.yaml (no need to specify anymore)
* Increase test brain timeouts to stop randomly failing tests
* Remove unused SANs from the generated TLS certificates
* Remove the dependency on jq from stemcells
* Fix duplicate buildpack ids when starting Cloud Foundry
* Fix an issue in the vagrant box where compilation would fail due to old versions of docker.
* Fix an issue where diego cell could not be mounted on nfs-backed Kubernetes storage class
* Fix an issue where diego cell could not mount nfs in persi
* Fix several problems reported with the syslog forwarding implementation

== 1.0 Release January, 2018

* Initial product release
