[id='sec.issue']
== Known Issues

IMPORTANT: You will need Stratos UI 1.1 when running {product} {version} and you
share the `scf-values.yaml` configuration file between them. Prior versions
of the Stratos UI will not work.

IMPORTANT: If you have used a configuration file from a version prior to
1.1, you will need to update it. See details below.

[id='sec.issue.upgrade']
=== Upgrade Changes

* The variable `kube.external_ip` has now been renamed to
`kube.external_ips`, meaning upgrades from older versions will fail unless
the latter variable exists in the `scf-values.yaml` file used to deploy
{product}. Both variables can exist at the same time and be set to the same
value for those in mixed version environments:
+
[source]
----
kube.external_ip=1.1.1.1
kube.external_ips=[1.1.1.1]
----

** Going forward, `kube.external_ips` is an array, hence it can be used as
reproduced below:
+
[source]
----
kube.external_ips=[“1.1.1.1”, “2.2.2.2”]
----

** Also as a result of this change, the `helm` command line client must be version 2.6.0 or higher.

** All the secrets have been renamed from `env.FOO` to `secrets.FOO`, so all
the appropriate entries in `scf-values.yaml` need to be modified to align with
that change.

** You need to keep specifying *all* your secrets on each upgrade (for example,
the `CLUSTER_ADMIN_PASSWORD`) as it will not be carried forward automatically.

** To rotate secrets, increment the `kube.secret_generation_counter`. Note
  that immutable generated secrets will not be reset.

* In HA environments, upgrades can run into an issue whereby the API pods do
  not all come up post-migration. The work around this issue, before the
  upgrade, scale down the API role to 1. After completing the upgrade, scale
  the API role up again to 2 or more.

** Some roles (like diego-api, diego-brain and routing-api) are configured as
active/passive, so passive pods can appear as `Not Ready`.

** Other roles (tcp-router and blobstore) cannot be scaled.

* Cloud Application Platform v1.1 requires that Stratos UI use version 1.1.
Older versions of the UI will not work due to the change in variable names.

* Azure operators may not be able to connect to SQL databases with the sidecar.

* Restores performed by the Backup CLI may leave docker apps in a stopped state.
The workaround is to restart the affected applications.

* A proper JSON file generated by the Backup CLI needs to be provided in order
to do a restore, otherwise an ugly error appears.

* Do not set the `mysql` or `diego_access` roles to more than one instance each
in HA configurations. Doing so can cause problems with subsequent upgrades
which could lead to loss of data. Scalability of these roles will be enabled
in an upcoming maintenance release.

* A `helm upgrade` command from 1.0 to 1.0.1 (scf 2.6.11 to 2.7.0) requires the
use of `--force` to drop an unnecessary persistent volume. Note that
`helm upgrade` only works for multi-node clusters when running with a proper
HA storage class (for example, `hostpath` will not work as required stateful
data can be lost).
