Release Notes: SUSE Cloud Application Platform 1.3
==================================================

include::entities.adoc[]
:azuredocurl: https://www.suse.com/documentation/cloud-application-platform-1/book_cap_guides/data/cha_cap_depl-azure.html


:docinfo:

This document provides guidance and an overview to high-level general
features and updates for {product} {version}. It also describes capabilities
and limitations of {product} {version}.
For detailed information about deploying this product, see the
_Deployment Guide_ at {deployment-url}.

These release notes are updated periodically. The latest version of
these release notes is always available at {rn-url}. General documentation
can be found at {doc-url}.


[id='sec.intro']
== About {product}

{product} is a modern application delivery platform used to bring an advanced
cloud native developer experience to {k8s}--the de-facto standard for
enterprise container orchestration. {product} eliminates manual IT
configuration and helps accelerate innovation by getting applications to
market faster. Developers can serve themselves and get apps to the cloud in
minutes instead of weeks, while staying within IT guidelines, and without
relying on scarce IT resources to perform manual configuration each step of
the way. Streamlining application delivery opens a clear path to increased
business agility, led by enterprise development, operations, and DevOps teams.

{product} increases business agility by helping enterprises to:

* Boost developer productivity with easy one step deployment of cloud native
applications using the language and framework most appropriate for the task.
* Reduce complexity and increase IT efficiency with a single, lean, platform
that brings together proven open source technologies for rapid application
delivery at scale.
* Maximize return on investment with industry leading open-source
technologies that leverage your existing investments.


include::support-statement.adoc[]


include::Release-Notes.adoc[]


[id='sec.caasp']
== Deploying {product} on {caasp}

For supported ways to deploy {product} on {caasp}, follow the deployment 
guides for your chosen infrastructure platform:

* https://www.suse.com/documentation/suse-caasp-3/book_caasp_deployment/data/book_caasp_deployment.html[Bare Metal or Non-OpenStack Virtualization Platforms]

* https://www.suse.com/documentation/suse-openstack-cloud-8/book_installation/data/sec_heat_templates_install.html[SUSE OpenStack Cloud]

Following the above guides will provide you with a fully supported {caasp} environment that you can subsequently use to install {product} using the {deployment-url}[{product} Deployment Guide].


== Installing {product} on {azure}

For instructions on installing {product} on {azure}, see the official
documentation at {azuredocurl}.


include::source-code.adoc[]

include::legal.adoc[]


[id='app.secret-sample']
== Appendix: Configuration with `secrets:` Section


[source,yaml]
----
include::values-sample.yaml[]
----

