Release Notes: SUSE Cloud Application Platform 1.3
==================================================

include::entities.adoc[]
:azuredocurl: https://www.suse.com/documentation/cloud-application-platform-1/book_cap_deployment/data/cha_cap_depl-azure.html


:docinfo:

This document provides guidance and an overview to high-level general
features and updates for {product} {version}. It also describes capabilities
and limitations of {product} {version}.
For detailed information about deploying this product, see the
_Deployment Guide_ at {deployment-url}.

These release notes are updated periodically. The latest version of
these release notes is always available at {rn-url}. General documentation
can be found at {doc-url}.


include::Release-Notes.adoc[]


[id='sec.caasp']
== Deploying {product} on {caasp}

For supported ways to deploy {product} on {caasp}, follow the deployment 
guides for your chosen infrastructure platform:

* https://www.suse.com/documentation/suse-caasp-3/book_caasp_deployment/data/book_caasp_deployment.html[Bare Metal or Non-OpenStack Virtualization Platforms]

* https://www.suse.com/documentation/suse-openstack-cloud-8/book_installation/data/sec_heat_templates_install.html[SUSE OpenStack Cloud]

Following the above guides will provide you with a fully supported {caasp} environment that you can subsequently use to install {product} using the {deployment-url}[{product} Deployment Guide].


== Installing {product} on {azure}

For instructions on installing {product} on {azure}, see the official
documentation at {azuredocurl}.


[id='app.secret-sample']
== Appendix: Configuration with `secrets:` Section


[source,yaml]
----
include::values-sample.yaml[]
----

